--260317
--급여가 3000이상인 모든 사원들을 조회
SELECT *
FROM EMP
WHERE (SAL >= 3000);

SELECT *
FROM EMP
ORDER BY SAL;
--사원이름이 FORZ문자열보다 앞에 있는 사원을 출력
SELECT *
FROM EMP
WHERE ENAME < 'FORZ';
--급여가 3000이 아닌 사원을 출력
SELECT *
FROM EMP
WHERE SAL <> 3000;
SELECT *
FROM EMP
WHERE SAL != 3000;
SELECT *
FROM EMP
WHERE SAL ^= 3000;
--NOT연산자
SELECT *
FROM EMP
WHERE NOT SAL = 3000;
--IN연산자
--사원 직책(JOB)이 MANAGER 또는 SALESMAN 또는 CLERK인 사원들을 출력
--IN연산자를 사용하는 경우와 사용하지 않는 경우 2가지를 작성
SELECT *
FROM EMP
WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
SELECT *
FROM EMP
WHERE JOB = 'MANAGER'
   OR JOB = 'SALESMAN'
   OR JOB = 'CLERK';
--사원 직책(JOB)이 MANAGER도 아니고 SALESMAN 나 CLERK이 아닌 사원들을 출력
--SELECT *
--FROM EMP
--WHERE NOT JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
SELECT *
FROM EMP
WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');
SELECT *
FROM EMP
WHERE JOB <> 'MANAGER'
  AND JOB <> 'SALESMAN'
  AND JOB <> 'CLERK';
SELECT *
FROM EMP
WHERE NOT (JOB = 'MANAGER'
  OR JOB = 'SALESMAN'
  OR JOB = 'CLERK');
--급여가 2000 이상 3000 이하인 사원을 출력
SELECT *
FROM EMP
WHERE SAL >= 2000 
  AND SAL <= 3000;

SELECT *
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;
--급여가 2000이상 3000미만인 사원을 출력
SELECT *
FROM EMP
WHERE (SAL BETWEEN 2000 AND 3000) 
  AND (SAL <> 3000);
SELECT *
FROM EMP
WHERE SAL >= 2000
  AND SAL < 3000;
-- 급여가 2000미만이거나 3000 초과하는 사원을 조회
SELECT *
FROM EMP
WHERE SAL < 2000
   OR SAL > 3000;
SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;
-- 사원이름이 대문자 S로 시작하는 사원 조회
SELECT *
FROM EMP
WHERE ENAME LIKE 'S%';
--사원이름의 두번째가 대문자 L인 사원 조회
SELECT *
FROM EMP
WHERE ENAME LIKE '_L%';
--사원이름에 'AM'이 포함되어 있는 사원 출력
SELECT *
FROM EMP
WHERE ENAME LIKE '%AM%';
SELECT *
FROM EMP
WHERE ENAME NOT LIKE '%AM%';
