--260324
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;
-- 사원이름이 SCOTT,scott,sCott,ScoTT인 사원 정보 조회
SELECT *
FROM EMP
WHERE UPPER(ENAME) = 'SCOTT';
SELECT *
FROM EMP
WHERE LOWER(ENAME) = 'scott';
-- sco가 이름에 포함된 사람
SELECT *
FROM EMP
WHERE UPPER(ENAME) LIKE '%SCO%';
--사원이름과 사원이름의 길이를 구하기
SELECT ENAME AS "사원이름",
	   LENGTH(ENAME) AS "사원이름 길이"
FROM EMP;
--사원이름의 길이가 5이상인 사원이름과 문자열의 길이 구하기
SELECT ENAME AS "사원이름",
	   LENGTH(ENAME) AS "사원이름 길이"
FROM EMP
WHERE LENGTH(ENAME) >= 5;
--SUBSTR
SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB,5), 
       SUBSTR(JOB,-1), SUBSTR(JOB,-1)
FROM EMP;
--사원이름의 끝 3자리를 조회
--단, 위치정보를 음수를 사용하지 않는다
SELECT ENAME, SUBSTR(ENAME, -3), SUBSTR(ENAME, LENGTH(ENAME)-2)
FROM EMP;
--INSTR
SELECT INSTR('HELLO, ORACLE', 'E', 1 , 2)
FROM DUAL;
--사원이름에 (대문자 A 또는 소문자 a가) 두개 이상 포함된 사원 조회 LIKE<->INSTR
SELECT *
FROM EMP
WHERE INSTR(UPPER(ENAME), 'A', 1, 2) > 0;
SELECT ENAME
FROM EMP
WHERE INSTR(UPPER(ENAME), 'A', 1, 2) <> 0;
-- REPLACE '문자열'
SELECT '010-1234-1234' AS BEFROE_TEXT,
	   REPLACE('010-1234-1234', '-', '_') AS REPLACE1,
	   REPLACE('010-1234-5678', '1234', '5678') AS REPLACE2,
	   REPLACE('010-1234-5678', '-') AS REPLACE3
FROM DUAL;