--260417
--각 사원정보와 사원의 직속상관(MGR)의 정보를 출력
SELECT e1.EMPNO AS "사원번호",
       e1.ENAME AS "사원이름", 
       e2.EMPNO AS "직속상관번호",
       e2.ENAME AS "상관이름"
FROM EMP e1, EMP e2
WHERE e1.MGR = e2.EMPNO;
--ADAMS라고 하는 사원의 직속상관 번호
SELECT e2.ENAME AS "상관이름"
FROM EMP e1, EMP e2
WHERE (e1.MGR = e2.EMPNO)
  AND UPPER(e1.ENAME) = 'ADAMS';
--SCOTT의 부하직원
SELECT e1.ENAME AS "사원이름"
FROM EMP e1, EMP e2
WHERE (e1.MGR = e2.EMPNO)
  AND UPPER(e2.ENAME) = 'BLAKE';
SELECT *
FROM EMP;
SELECT e1.EMPNO AS "사원번호",
       e1.ENAME AS "사원이름", 
       e2.EMPNO AS "직속상관번호",
       e2.ENAME AS "상관이름"
FROM EMP e1, EMP e2
WHERE (e1.MGR(+) = e2.EMPNO);
--부하직원이없는 사원의 명단 출력
SELECT e2.ENAME AS "상관 이름"
FROM EMP e1, EMP e2
WHERE (e1.MGR(+) = e2.EMPNO) 
  AND e1.EMPNO IS NULL;
SELECT ENAME
FROM EMP
WHERE MGR IS NULL;
--SQL-99 표준문법
SELECT DEPTNO
FROM EMP E NATURAL JOIN DEPT D;
-- 99이전 등가
SELECT D.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
SELECT DEPTNO
FROM EMP JOIN DEPT USING (DEPTNO);
SELECT EMP.DEPTNO
FROM EMP JOIN DEPT ON (EMP.DEPTNO = DEPT.DEPTNO);
--비등가 JOIN ON
SELECT *
FROM EMP JOIN SALGRADE ON (EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL);

