--260410
--7장 Q1
SELECT DEPTNO,
       TRUNC(AVG(SAL), 0) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC;
--Q2
SELECT JOB,
       COUNT(*)
FROM EMP
GROUP BY JOB
	HAVING COUNT(*) >= 3;
--Q3
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;
--Q4
--SELECT NVL2(COMM, 'O', 'X'),
--	   COUNT(*)
--FROM EMP
--GROUP BY NVL2(COMM, 'O', 'X')
--ORDER BY COUNT(*) DESC;
--
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
	   COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X')
ORDER BY NVL2(COMM, 'O', 'X') DESC;