--260414
SELECT *
FROM EMP, DEPT;
--몇개의레코드가나오는가
SELECT COUNT(*)
FROM EMP, DEPT;
SELECT *
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;
SELECT *
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO;
-- SMITH가 어디근무하는가
SELECT ENAME, LOC AS "근무지"
FROM EMP, DEPT
WHERE ( EMP.DEPTNO = DEPT.DEPTNO )
  AND UPPER(EMP.ENAME) = 'SMITH';
-- DALLAS에 근무하는 사원들을 조회
SELECT ENAME, LOC
FROM EMP, DEPT
WHERE ( EMP.DEPTNO = DEPT.DEPTNO )
  AND DEPT.LOC = 'DALLAS';
-- 비등가조인 / JONES의 등급
SELECT e.ENAME,
       s.GRADE 
FROM EMP e, SALGRADE s
WHERE (e.SAL BETWEEN s.LOSAL AND s.HISAL)
  AND UPPER(e.ENAME) = 'JONES';