--260515
CREATE TABLE EMP_AA AS SELECT * FROM EMP;
CREATE TABLE DEPT_AA AS SELECT * FROM DEPT;
CREATE TABLE SALGRADE_AA AS SELECT * FROM SALGRADE;
DROP TABLE DEPT_AA;
DROP TABLE EMP_AA;
DROP TABLE SALGRADE_AA;
SELECT * FROM SALGRADE_AA;
SELECT * FROM DEPT_AA;
-- DEPT 복사 테이블에 50,60,70,80번 부서 등록
SELECT * FROM EMP;
INSERT INTO DEPT_AA(DEPTNO, DNAME, LOC)
VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO DEPT_AA(DEPTNO, DNAME, LOC)
VALUES (60, 'SQL', 'ILSAN');
INSERT INTO DEPT_AA(DEPTNO, DNAME, LOC)
VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO DEPT_AA(DEPTNO, DNAME, LOC)
VALUES (80, 'DML', 'BUNDANG');
--
SELECT * FROM EMP_AA;
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016/01/02','YYYY/MM/DD'), 4500, NULL, 50);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016/02/21','YYYY/MM/DD'), 1800, NULL, 50);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016/04/11','YYYY/MM/DD'), 3400, NULL, 60);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016/05/31','YYYY/MM/DD'), 2700, 300, 60);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016/07/20','YYYY/MM/DD'), 2600, NULL, 70);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016/09/08','YYYY/MM/DD'), 2600, NULL, 70);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016/10/28','YYYY/MM/DD'), 2300, NULL, 80);
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018/03/09','YYYY/MM/DD'), 1200, NULL, 80);
--Q3
SELECT * FROM EMP_AA ORDER BY DEPTNO;
SELECT AVG(SAL)
FROM EMP_AA E
WHERE DEPTNO = 50;
SELECT *
FROM EMP_AA 
WHERE SAL > (SELECT AVG(SAL)
		     FROM EMP_AA E
			 WHERE DEPTNO = 50);
UPDATE EMP_AA E
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
	         FROM EMP_AA E
	         WHERE DEPTNO = 50);
--입사일이 가장 빠른 60번 부서 사원보다 늦게 입사한 사원의 급여 10% 인상하고 80번 부서로 옮김
SELECT ENAME, MIN(HIREDATE)
FROM EMP_AA
WHERE DEPTNO = 60
GROUP BY ENAME;
SELECT MIN(HIREDATE)
FROM EMP_AA
WHERE DEPTNO = 60;
SELECT HIREDATE
FROM EMP_AA
WHERE HIREDATE > (SELECT HIREDATE FROM EMP_AA WHERE DEPTNO=60);
SELECT *
FROM EMP_AA 
WHERE HIREDATE > (SELECT MIN(HIREDATE)
				  FROM EMP_AA
				  WHERE DEPTNO = 60);
UPDATE EMP_AA 
SET SAL = SAL*1.1,
    DEPTNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE)
				  FROM EMP_AA
				  WHERE DEPTNO = 60);
--EMP 급여등급이 5인 사원 삭제
SELECT EMPNO
FROM EMP_AA E JOIN SALGRADE_AA S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE S.GRADE = 5;
DELETE EMP_AA 
WHERE EMPNO IN (SELECT EMPNO
			    FROM EMP_AA E JOIN SALGRADE_AA S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
				WHERE S.GRADE = 5);
DELETE EMP_AA 
WHERE EMPNO IN (SELECT EMPNO 
			    FROM EMP_AA E, SALGRADE_AA S
				WHERE (E.SAL BETWEEN S.LOSAL AND S.HISAL)
				  AND S.GRADE = 5);
SELECT * FROM EMP_AA;

