--260505 SUBQUERY
-- JONES의 급여
SELECT SAL
FROM EMP
WHERE ENAME = 'JONES';
-- JONES 보다 급여가 높은 사원을 조회
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL 
		     FROM EMP
             WHERE UPPER(ENAME) = 'JONES');
--
-- 서브쿼리를 사용하여 사원이름이 ALLEN인 사원의 추가 수당보다 많은 수당을 받는 사원 정보 조회
SELECT *
FROM EMP
WHERE COMM > (SELECT COMM 
			  FROM EMP 
			  WHERE UPPER(ENAME) = 'ALLEN');
--20번 부서에 속한 사원 중 / 전체 사원의 평균 급여보다 / 높은 급여 /를 받는 사원의 이름과 부서의 이름을 조회
-- 단일행 연산자
SELECT AVG(SAL)
FROM EMP;

SELECT ENAME, DNAME
FROM EMP E, DEPT D
WHERE (E.DEPTNO = D.DEPTNO)
  AND (E.DEPTNO = 20 )
  AND SAL > (SELECT AVG(SAL)
			 FROM EMP);
-- NATURAL JOIN 사용

-- 다중행 서브쿼리
-- 부서번호가 30인 사원들의/ 최소 급여보다 적은 급여를/ 받는 사원을 서브쿼리를 이용해서 조회 (반드시 다중행연산 사용)
SELECT DISTINCT SAL
FROM EMP
WHERE DEPTNO = 30;

SELECT ENAME, SAL
FROM EMP
WHERE SAL < ALL(SELECT DISTINCT SAL
				FROM EMP
				WHERE DEPTNO = 30);

--10번 부서의 사원보다 일찍 입사한 사원의 정보 조회
SELECT HIREDATE
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < ALL(SELECT HIREDATE
					 FROM EMP
					 WHERE DEPTNO = 10);
-- 다중열 서브쿼리
-- 각 부서별 최고 급여를 수령하는 사원의 정보
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
 					    FROM EMP
 					    GROUP BY DEPTNO);

-- 모든 사원의 사원이름과 / 급여등급을 표시/ 단, 조인 연산 X
SELECT ENAME,
	   (SELECT GRADE FROM SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL) AS "SALGRADE"
FROM EMP E;

SELECT EMPNO,ENAME,JOB,SAL,
	   (SELECT GRADE FROM SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL) AS "SALGRADE",
	   DEPTNO,
	   (SELECT DNAME FROM DEPT D WHERE E.DEPTNO = D.DEPTNO) AS DNAME
FROM EMP E;

SELECT ENAME, GRADE
FROM EMP E JOIN SALGRADE S ON (SAL BETWEEN LOSAL AND HISAL);

--

