--260526
DROP TABLE TABLE_AA;
CREATE TABLE TABLE_AA(
	LOGIN_ID VARCHAR(20) CONSTRAINT LOGID_NN NOT NULL,
	LOGIN_PWD VARCHAR(20) CONSTRAINT LOGPW_NN NOT NULL,
	TEL VARCHAR(20)
);

SELECT *
FROM TABLE_AA;

INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('ABCD', '1234', NULL);

INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL)
VALUES (NULL, NULL, NULL);

UPDATE TABLE_AA
SET TEL = '010-1234-5678'
WHERE TEL IS NULL;

DELETE TABLE_AA 
WHERE TEL IS NULL;

SELECT LOGIN_ID, LOGIN_PWD, TEL
FROM TABLE_AA;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_AA';

--tel에 not null 제약 조건 추가하기
ALTER TABLE TABLE_AA 
MODIFY TEL VARCHAR(20) CONSTRAINT TEL_NN NOT NULL;

ALTER TABLE TABLE_AA 
MODIFY (TEL CONSTRAINT TEL_NN NOT NULL);

SELECT * FROM TABLE_AA;

INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL)
VALUES (NULL, NULL, NULL);

ALTER TABLE TABLE_AA
DROP CONSTRAINT TEL_NN;
-- UNIQUE PRIMARY KEY
-- FOREIGN KEY
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TABLE_AA';
CREATE TABLE TABLE_AA(
	LOGIN_ID VARCHAR(20) CONSTRAINT LOGID_PK PRIMARY KEY,
	LOGIN_PWD VARCHAR(20) CONSTRAINT LOGPW_NN NOT NULL,
	TEL VARCHAR(20),
	DEPTNO NUMBER(2,0) CONSTRAINT DEPTNO_FK REFERENCES DEPT (DEPTNO)
);

SELECT DEPTNO FROM DEPT;
--DEPTNO { 10, 20, 30, 40 }
SELECT *
FROM TABLE_AA;
--무결성 제약조건(FK)위반
INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL, DEPTNO)
VALUES('ABCD', '1234', NULL, 50);
--
INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL, DEPTNO)
VALUES('ABCD', '1234', NULL, 40);

INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, TEL, DEPTNO)
VALUES('EFGH', '1234', NULL, NULL);

ALTER TABLE TABLE_AA
RENAME COLUMN DEPTNO TO DEPTNO_FK;

--INSERT INTO TABLE_AA(LOGIN_ID, LOGIN_PWD, DEPTNO)
--VALUES('EFGH', '1234', NULL);