--260519 데이터 정의어
CREATE TABLE MY_EMP_AA (
 EMPNO NUMBER(4,0),
 ENAME VARCHAR2(10),
 JOB VARCHAR2(9),
 MGR NUMBER(4,0),
 HIREDATE DATE,
 SAL NUMBER(7,2),
 COMM NUMBER(7,2),
 DEPTNO NUMBER(2,0)
);
SELECT * FROM MY_EMP_AA;
SELECT * FROM DEPT;
-- INSERT 하기
INSERT INTO MY_EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, TEL)
VALUES (1234, '정주호', '학생', 1001, TO_DATE('2026/05/19','YYYY/MM/DD'), 500, NULL, 20, '01012345678');
DELETE MY_EMP_AA 
WHERE EMPNO = 1234;
ALTER TABLE MY_EMP_AA 
ADD HP NUMBER(11,0);
UPDATE MY_EMP_AA 
SET HP = 01012345678
WHERE EMPNO = 1234;
ALTER TABLE MY_EMP_AA
MODIFY HP VARCHAR(11);
ALTER TABLE MY_EMP_AA 
RENAME COLUMN HP TO TEL;
ALTER TABLE MY_EMP_AA 
MODIFY TEL VARCHAR(15);
ALTER TABLE MY_EMP_AA 
DROP COLUMN TEL;

TRUNCATE TABLE MY_EMP_AA;
ROLLBACK;