--260512
--상단탭 데이터베이스 > 트랜잭션 모드 > 매뉴얼 커밋 선택
--DEPT 테이블을 복사하여 새로운 DEPT_AA 테이블 생성
CREATE TABLE DEPT_AA
	AS SELECT * FROM DEPT WHERE 1=1;

SELECT * FROM DEPT_AA;
SELECT * FROM DEPT;
--
DROP TABLE DEPT_AA;
--INSERT문
--INSERT INTO 테이블이름 (열1,열2,열3)
--VALUES (DATA,DATA,DATA) 

--DEPT_AA 테이블에 부서번호 50, 부서이름 DATABASE, 지역 SEOUL 데이터 추가
INSERT INTO DEPT_AA (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

INSERT INTO DEPT_AA 
VALUES (60, 'JAVA', 'BUSAN');

INSERT INTO DEPT_AA (DEPTNO, LOC, DNAME)
VALUES (70, 'ILSAN', 'C++');

--EMP 테이블의 구조만 복사하여 EMP_AA 테이블 생성
CREATE TABLE EMP_AA
    AS SELECT * FROM EMP WHERE 1<>1;

SELECT * FROM EMP_AA;

DROP TABLE EMP_AA;

INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1001, '정주호', '학생', NULL, '2024-03-01', 0, 0, 50);
--맞는답 문자열X > date type 맞춰서
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1001, '정주호', '학생', NULL, TO_DATE('2024-03-01', 'YYYY-MM-DD'), 0, 0, 50);

--서브쿼리 values 사용하지않음
INSERT INTO EMP_AA(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
		  FROM EMP E JOIN SALGRADE S ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
         WHERE S.GRADE = 1;;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP E JOIN SALGRADE S ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE S.GRADE = 1;
--
DELETE FROM EMP_AA
WHERE ENAME LIKE '정%';
SELECT *
FROM EMP_AA;
--
CREATE TABLE EMP_AA2
    AS SELECT * FROM EMP WHERE 1=1;
DROP TABLE EMP_AA2;
SELECT *
FROM EMP_AA2;
--EMP_AA2테이블에서 급여 등급이 3등급인 30번 부서의 사원들 삭제
DELETE FROM EMP_AA2
WHERE ENAME IN (SELECT ENAME
				FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
				WHERE S.GRADE = 3 AND E.DEPTNO = 30);

SELECT ENAME
FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE S.GRADE = 3 AND E.DEPTNO = 30;