--260522
--다음 열 구조를 가지는 EMP_HW 테이블을 만들어 보세요.
CREATE TABLE EMP_HW(
 EMPNO NUMBER(4,0),
 ENAME VARCHAR(10),
 JOB VARCHAR(9),
 MGR NUMBER(4,0),
 HIREDATE DATE,
 SAL NUMBER(7,2),
 COMM NUMBER(7,2),
 DEPTNO NUMBER(2,0)
);
SELECT * FROM EMP_HW;
-- EMP_HW 테이블에 BIGO열을 추가해 보세요. BIGO 열의 자료형은 가변형 문자열이고, 길이는 20

ALTER TABLE EMP_HW
ADD BIGO VARCHAR(20);

-- EMP_HW 테이블의 BIGO 열 크기를 30으로 변경해 보세요.

ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR(30);

-- BIGO 열 이름을 REMARK로 변경

ALTER TABLE EMP_HW -- CREATE ALTER DROP RENAME TRUNCATE / DDL LEVEL 'RENAME' <> ALTER 하위 'RENAME'
RENAME COLUMN BIGO TO REMARK;

-- REMARK 열 삭제
ALTER TABLE EMP_HW
DROP COLUMN REMARK;
ALTER TABLE EMP_HW
ADD REMARK VARCHAR(30);
-- 테이블에 데이터 저장하기 remark열은 null로 .데이터 insert
SELECT * FROM EMP_HW;
INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, REMARK)
VALUES (1004,'정주호', '학생', 7369, TO_DATE('2020-05-04', 'YYYY-MM-DD'), 800, NULL, 20, NULL);
INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, REMARK)
VALUES (1005,'하니니', '학생', 7369, TO_DATE('2021-05-04', 'YYYY-MM-DD'), 100, NULL, 20, NULL);

-- remark 값을 duica로 변경
UPDATE EMP_HW 
SET REMARK = 'DUICA'
WHERE ENAME = '하니니';


-- remark 값이 null인 row 삭제
DELETE FROM EMP_HW 
WHERE REMARK IS NULL;

-- 사용한 테이블 삭제
DROP TABLE EMP_HW;
