--260529 12장 연습문제
-- DEPT_CONST 테이블 생성
CREATE TABLE DEPT_CONST(
  DEPTNO NUMBER(2,0) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
  DNAME VARCHAR(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
  LOC VARCHAR(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);
DROP TABLE DEPT_CONST;
SELECT * FROM DEPT_CONST;
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT_CONST';
INSERT INTO DEPT_CONST(DEPTNO, DNAME, LOC)
VALUES (30, 'SCHOOL', 'SEOUL');
--EMP_CONST 테이블 생성
DROP TABLE EMP_CONST;
CREATE TABLE EMP_CONST(
  EMPNO NUMBER(4,0) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
  ENAME VARCHAR(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
  TEL VARCHAR(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
  SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (SAL BETWEEN 1000 AND 9999),
  DEPTNO NUMBER(2,0) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST (DEPTNO)
);
DROP TABLE EMP_CONST;
SELECT * FROM EMP_CONST;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP_CONST';
SELECT DEPTNO FROM DEPT_CONST;
--체크 제약조건(SCOTT.EMPCONST_SAL_CHK)이 위배
INSERT INTO EMP_CONST (EMPNO, ENAME, TEL, SAL, DEPTNO)
VALUES (2345, 'ABCDE', '010-3456-7890', 10000, 30);
--
INSERT INTO EMP_CONST (EMPNO, ENAME, TEL, SAL, DEPTNO)
VALUES (1234, 'ADMIN', '010-1234-1232', 5000, 30);
INSERT INTO EMP_CONST (EMPNO, ENAME, TEL, SAL, DEPTNO)
VALUES (4444, 'KIM', '010-2323-3434', 4444.44, 30);
--
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('EMP_CONST','DEPT_CONST'); 