--SYSTEM 계정 -- SCOTT의 테이블 조회안됨
GRANT CREATE VIEW TO SCOTT;
REVOKE CREATE VIEW FROM SCOTT;

SELECT * FROM DBA_TABLES;
SELECT * FROM DBA_USERS;

GRANT CREATE SEQUENCE TO SCOTT;
REVOKE CREATE SEQUENCE FROM SCOTT;