--SYS
CREATE USER USER_AA
IDENTIFIED BY ORACLE
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO USER_AA;

GRANT CREATE TABLE TO USER_AA;

--ROLE 부여
GRANT RESOURCE TO USER_AA;

-- 시스템 권한 취소
REVOKE CREATE TABLE, RESOURCE FROM USER_AA;
REVOKE CREATE SESSION FROM USER_AA;
DROP USER USER_AA;

--ROLE 생성