--읽기 일관성 실습
SELECT * FROM dept_tcl;

--LOCK
UPDATE DEPT_TCL
SET DNAME = 'DATABASE'
WHERE DEPTNO = 30;
--세션 1에서 같은 ROW TR 중 LOCK됨
ROLLBACK;
-- 서로 다른 ROW에 대해서는 LOCK 안됨
UPDATE DEPT_TCL
SET DNAME = 'DATABASE'
WHERE DEPTNO = 10;
ROLLBACK;
--연습문제
SELECT * FROM DEPT_HW;
UPDATE DEPT_HW
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 30;

COMMIT;
SELECT * FROM DEPT_HW;