--260602
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM user_indexes;
SELECT * FROM USER_IND_COLUMNS;
--SYS로 부터 CREATE VIEW 권한 부여
CREATE VIEW VW_EMP10
    AS (SELECT EMPNO, ENAME
        FROM EMP
        WHERE DEPTNO = 10);

SELECT * FROM VW_EMP10;
SELECT * FROM USER_VIEWS;
SELECT * FROM ALL_VIEWS;
SELECT * FROM ALL_TABLES;

DROP VIEW VW_EMP10;

-- EMP SAL 최고급여자 3명만 검색
-- 인라인뷰 // order by 절 포함은 view로 X
SELECT ROWNUM, EMP_ORDERBY_SAL.*
FROM (SELECT * FROM EMP ORDER BY SAL DESC) EMP_ORDERBY_SAL
WHERE ROWNUM <= 3;

WITH EMP_ORDERBY_SAL AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, EMP_ORDERBY_SAL.*
FROM EMP_ORDERBY_SAL
WHERE ROWNUM <= 3;

--SEQUENCE
CREATE TABLE DEPT_TEMP(DEPTNO, DNAME, LOC)
AS (SELECT * FROM DEPT WHERE 1<>1);
SELECT * FROM DEPT_TEMP;
CREATE SEQUENCE DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 200
MINVALUE 0
CYCLE;
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES (DEPT_SEQUENCE.NEXTVAL, '이름', '지역');
SELECT * FROM DEPT_TEMP;
DROP TABLE DEPT_TEMP;
DROP SEQUENCE DEPT_SEQUENCE;
--SYNONYM