--CREATED USER// USER_AA
ID PRIMARY KEY
PW NN 

CREATE TABLE TABLE_AA(
	ID VARCHAR(16) CONSTRAINTS id_TABLEAA_PK PRIMARY KEY,
	PW VARCHAR(16) CONSTRAINTS pw_TABLEAA_NN NOT NULL
);
DROP TABLE TABLE_AA;
SELECT * FROM TABLE_AA;
SELECT * FROM SYS.USER_CONSTRAINTS;

--TABLESPACE 권한 없음 > 리소스(롤) 부여
INSERT INTO TABLE_AA(ID, PW)
VALUES ('AANEWID', 'asdf1234');
--리소스 권한 REVOKE 후 INSERT , 이미 리소스 공간이 부여됐기 때문에 INSERT 됨
INSERT INTO TABLE_AA(ID, PW)
VALUES ('ZXCV', 'ASDF');

CREATE TABLE TABLE_AA2(
	ID VARCHAR(16) CONSTRAINTS id_TABLEAA2_PK PRIMARY KEY,
	PW VARCHAR(16) CONSTRAINTS pw_TABLEAA2_NN NOT NULL
);
DROP TABLE TABLE_AA2;
-- 새로운 테이블 리소스 권한없음 , INSERT 안됨
INSERT INTO TABLE_AA2(ID, PW)
VALUES ('AANEWID', 'asdf1234');
-- SCOTT에게 TABLE_AA 객체 SELECT 할 수 있는 권한 부여
GRANT SELECT 
   ON USER_AA.TABLE_AA
   TO SCOTT;
--
REVOKE SELECT
   ON TABLE_AA
  FROM SCOTT;
