--260605
--SCOTT

CREATE TABLE dept_tcl
AS SELECT * FROM DEPT WHERE 1=1;

SELECT *
FROM DEPT_TCL;
-- 갱신연산 , 트랜잭션 시작
INSERT INTO dept_tcl (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', '서울');

UPDATE DEPT_TCL
SET LOC = 'BUSAN'
WHERE DEPTNO = 40;

DELETE DEPT_TCL
WHERE DNAME = 'RESEARCH';

DELETE DEPT_TCL;

ROLLBACK;

COMMIT;
--COMMIT 영구히 완료, ROLLBACK 안됨

--읽기 일관성 세션 2개
SELECT * FROM DEPT_TCL;
--갱신연산 TR 시작 , 부서번호 50인 부서의 정보를 삭제 
DELETE DEPT_TCL
WHERE DEPTNO = 50;
ROLLBACK;

--LOCK
UPDATE DEPT_TCL
SET LOC = 'SEOUL'
WHERE DEPTNO = 30;
COMMIT;
--
UPDATE DEPT_TCL
SET LOC = 'BUSAN'
WHERE DEPTNO = 30;
ROLLBACK;
--연습문제
CREATE TABLE DEPT_HW
AS SELECT * FROM DEPT WHERE 1=1;

SELECT * FROM DEPT_HW;

UPDATE DEPT_HW
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 30;

ROLLBACK;

DROP TABLE DEPT_HW;
DROP TABLE DEPT_TCL;