--260320
SELECT * 
  FROM EMP; 
-- 수당이 존재하지 않는 사원 정보 조회 > IS NULL
SELECT *
  FROM EMP
 WHERE COMM IS NULL;

SELECT *
  FROM EMP
 WHERE COMM IS NOT NULL
   AND COMM > 0;
-- 수당을 받지 않는 사원 정보 조회
SELECT *
  FROM EMP
 WHERE COMM IS NULL
    OR (COMM = 0);
-- 직속상관이 있는 사원 데이터 조회
SELECT *
  FROM EMP
 WHERE MGR IS NOT NULL;
-- AND <-> OR
SELECT *
  FROM EMP
 WHERE SAL NULL
   AND COMM IS NULL;
-- 연습문제
-- EMP 테이블의 JOB 열 데이터를 중복 없이 출력하기
SELECT DISTINCT JOB 
  FROM EMP;
-- 조회할 테이블은 EMP테이블이며 출력되는 열의 별칭은 다음과 같고
-- 부서 번호를 기준으로 내림차순으로 정렬하되 부서번호가 같다면 사원이름을 오름차순 정렬
SELECT EMPNO AS "EMPLOYEE_NO"
  	  ,ENAME AS "EMPLOYEE_NAME"
  	  ,MGR AS "MANAGER"
  	  ,SAL AS "SALARY"
  	  ,DEPTNO AS "DEPARTMENT_NO"
FROM EMP
ORDER BY DEPTNO DESC, ENAME;
-- EMP 테이블을 사용하여 다음과 같이 사원이름이 S로 끝나는 사원 데이터를 모두 출력하는 SQL문을 작성
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';
--Q2
SELECT EMPNO,ENAME, JOB, SAL, DEPTNO
FROM EMP 
WHERE DEPTNO = 30 
  AND JOB = 'SALESMAN';
--Q3
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE (DEPTNO = 20
   OR DEPTNO = 30)
  AND SAL > 2000;
--Q4
SELECT *
FROM EMP
WHERE SAL < 2000
   OR SAL > 3000;
SELECT *
FROM EMP 
WHERE SAL NOT BETWEEN 2000 AND 3000;
--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE (ENAME LIKE '%E%' 
  AND DEPTNO = 30)
  AND SAL NOT BETWEEN 1000 AND 2000;
--Q6 존재하지 않고 / 없고
SELECT *
FROM EMP
WHERE COMM IS NULL
  AND MGR IS NOT NULL
  AND JOB IN ('CLERK', 'MANAGER')
  AND ENAME NOT LIKE '_L%';

