-- 260331 ROUND TRUNC CEIL FLOOR MOD
SELECT ROUND( 1234.5678, 1)
      ,ROUND( 1234.5678, 0)
      ,ROUND(1234.5678)
      ,ROUND(1234.567, -4)
FROM DUAL;
SELECT ROUND(SAL, -2)
FROM EMP;
-- 날짜함수 ADD_MONTHS MONTHS_BETWEEN
SELECT SYSDATE
      ,SYSDATE+1 AS TOMORROW
      ,SYSDATE-1
FROM EMP;
--
SELECT ADD_MONTHS(SYSDATE, 3)
FROM DUAL;
--사원 테이블에서 사원들의 입사 10주년이 되는 날짜를 조회
SELECT ENAME
	  ,HIREDATE AS "고용일자"
      ,ADD_MONTHS(HIREDATE , (10*12)) AS "10주년"
      ,ADD_MONTHS(HIREDATE , (10*12))-HIREDATE AS "차이"
FROM EMP;
--입사 42년 미만인 사원 출력
SELECT *
FROM EMP
WHERE (SYSDATE - HIREDATE) < (ADD_MONTHS(HIREDATE , (42*12))-HIREDATE);
SELECT ENAME , SYSDATE, HIREDATE, ADD_MONTHS(HIREDATE, (42*12))
FROM EMP
WHERE (SYSDATE - ADD_MONTHS(HIREDATE, (42*12))) < 0;
SELECT ENAME
FROM EMP
WHERE ADD_MONTHS(HIREDATE, (42*12)) > SYSDATE;

--사원이 입사한지 지난 개월 수 출력 정수로 표현 FLOOR
SELECT ENAME
	  ,TRUNC(SYSDATE)
      ,MONTHS_BETWEEN(SYSDATE, HIREDATE) AS BET
	  ,MONTHS_BETWEEN(HIREDATE, SYSDATE) AS BET
	  ,TRUNC(MONTHS_BETWEEN(HIREDATE, SYSDATE)) AS "TRUNC"
	  ,FLOOR(MONTHS_BETWEEN(HIREDATE, SYSDATE)) AS "FLOOR"
FROM EMP;
--NEXT_DAY LAST_DAY
SELECT SYSDATE
      ,NEXT_DAY(SYSDATE, '월요일')
      ,LAST_DAY('280201')
FROM DUAL;
--TO_CHAR 형변환
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')
FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY"년"MM"월"DD"일" HH24:MI:SS')
FROM DUAL;
--사원 5월 입사 이름
SELECT ENAME
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM') = '05';
--
SELECT SYSDATE
      ,TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일" (DY) DAY')
      ,TO_CHAR(SYSDATE, 'HH24"시" MI"분" SS"초"')
FROM DUAL;
--
SELECT SAL
	  ,TO_CHAR(SAL, '$999,999') AS SAL2
	  ,TO_CHAR(SAL, '$999,999.00') AS SAL3
FROM EMP;
--사원들의 급여를 100만 단위로 출력
SELECT SAL 
	  ,TO_CHAR(SAL, '9,999') || '만원'
FROM EMP;
