--260310
SELECT DEPTNO	
FROM EMP;

SELECT DISTINCT DEPTNO
FROM EMP;

SELECT DISTINCT DEPTNO
FROM EMP
ORDER BY DEPTNO DESC;

SELECT DISTINCT JOB, DEPTNO
FROM EMP;

SELECT ENAME, (SAL+COMM) AS "실수령액"
FROM EMP;

SELECT ENAME, SAL, COMM, (SAL+COMM) AS RSAL
FROM EMP;

SELECT ENAME AS "사원 이름", SAL+COMM AS "실수령액"
FROM EMP;