-- 260403
--DATA TYPE에 신경쓴다
SELECT TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999') AS TONUM
      ,1300 - 1500
FROM DUAL;
--
SELECT TO_DATE('2021-09-22', 'YYYY-MM-DD') AS DAY1
      ,TO_DATE('202109/23', 'YYYY-MM/DD') AS DAY2
FROM DUAL;
-- 
SELECT ENAME, HIREDATE
FROM EMP e 
WHERE HIREDATE > TO_DATE('1985-01-01', 'YYYY-MM-DD');
SELECT ENAME, HIREDATE
FROM EMP e 
WHERE HIREDATE > TO_DATE('01-06-1985', 'MM-DD-YYYY');
--입사일이 1985년 02월 01일(02-01-1985 형식) 이후 입사한 사람의 정보를 조회 
--오라클에서 자료형 변환은 발생하지 않는다고 가정한다.
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > TO_DATE('02-01-1985', 'MM-DD-YYYY');
-- NVL
SELECT EMPNO
	  ,ENAME
	  ,SAL
	  ,COMM
	  ,SAL+COMM
	  ,NVL(COMM,0)
	  ,SAL+NVL(COMM,0)
FROM EMP;
-- NVL2
SELECT EMPNO, ENAME, SAL, COMM,
       NVL2(COMM, 'O', 'X')
FROM EMP;
-- 각 사원의 1년 소득을 조회 SAL은 월 소득
SELECT ENAME, SAL, COMM,
	   NVL2(COMM, SAL*12+COMM, SAL*12) AS "1년 소득"
FROM EMP;
--6장 Q1
SELECT EMPNO
      ,RPAD(SUBSTR(EMPNO,1,2), 4, '*') AS MASKING_EMPNO
      ,ENAME
      ,RPAD(SUBSTR(ENAME, 1, 1), 5, '*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;
--6장 Q2
SELECT EMPNO
      ,ENAME 
      ,SAL
      ,TRUNC((SAL/21.5),2) AS DAY_PAY
      ,ROUND((SAL/21.5)/8, 1) AS TIME_PAY
FROM EMP;
--6장 Q3
SELECT EMPNO
      ,ENAME
      ,HIREDATE
      ,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'),'YYYY-MM-DD') AS R_JOB
      ,NVL2(COMM, TO_CHAR(COMM), 'N/A')
FROM EMP;